Download all "real" extensions and skins via Git and not Composer
WikiWorks/Canasta pull request #280
Opened 2023-08-18 18:49 UTC by yaronkoren

The only extensions that are still downloaded via Composer are "helper"/library extensions like DataValues, ParserHooks and Bootstrap (which is to some extent a helper extension).

This change requires a corresponding change to the Canasta-DockerCompose repository to remove all extensions and skins from the file composer.local.json.

2023-08-23 18:36 UTC, vedmaka requested changes

2023-08-23 18:36 UTC, vedmaka commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticCompoundQueries $MW_HOME/extensions/SemanticCompoundQueries \
It seems `SemanticCompoundQueries` is missing from the `composer.canasta.json` file

2023-08-23 18:36 UTC, vedmaka commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties $MW_HOME/extensions/SemanticExtraSpecialProperties \
`SemanticExtraSpecialProperties` is also missing from the `composer.canasta.json` file

2023-08-23 18:36 UTC, vedmaka commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticScribunto $MW_HOME/extensions/SemanticScribunto \
`SemanticScribunto` is missing from the composer file

2023-08-23 18:54 UTC, yaronkoren commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties $MW_HOME/extensions/SemanticExtraSpecialProperties \
This extension doesn't need to be added to a Composer JSON file, does it? It doesn't seem like it has any special dependencies.

2023-08-23 18:55 UTC, yaronkoren commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticScribunto $MW_HOME/extensions/SemanticScribunto \
Same question as above.

2023-08-23 21:09 UTC, cicalese commented on Dockerfile
> +# SemanticBreadcrumbLinks
You have to patch the composer.json files before you run composer update.

2023-08-23 22:17 UTC, yaronkoren commented on Dockerfile
> +# SemanticBreadcrumbLinks
Good point! I just fixed this, I think. I also removed the 2nd call to "composer update", which I believe is no longer needed.

2023-08-23 22:24 UTC, cicalese commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
There's nothing left required here. This patch should be removed, and the extension should be removed from composer.local.json.

2023-08-23 22:24 UTC, cicalese commented on _sources/patches/semantic-forms-select-composer-reqs.patch
> + 	},
There are no dependent libraries left here. This patch should be removed, and the extension should be removed from composer.local.json.

2023-08-23 22:31 UTC, yaronkoren commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
That's true... both of these extensions are there (and patched) because of the whole "autoload" brouhaha, as discussed at #274. It would be great if @vedmaka could respond to your question there. (Or here, for that matter.) I just don't want to break anything.

2023-08-24 04:30 UTC, cicalese commented on _sources/configs/composer.canasta.json
>  			"include": [
If you add:

      "require": {
               "psr/http-message": "1.1"
       },
 
at line 2 of this file, it will prevent an error caused by conflicting versions of this library. As far as I can tell, DataTransfer requires this version, but another extension or library is handled first and pulls version 2.0 instead. Pegging this to version 1.1 works without conflict.

2023-08-24 04:32 UTC, cicalese commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
Oh, that's right. I forgot that conversation was still pending. For what its worth, I tested this patch with those two lines removed, and I was able to load both extensions successfully. They both reported they were loaded on Special:Version. But, I don't know what to test to ensure that an error does not occur when the extensions are otherwise exercised.

2023-08-24 05:25 UTC, yaronkoren commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticCompoundQueries $MW_HOME/extensions/SemanticCompoundQueries \
Same question as for the other two.

2023-08-24 13:41 UTC, yaronkoren commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
Okay, that's very good to know. I think if they show up on Special:Version, that's pretty much the only test that matters... @vedmaka, I really do hope you respond to this.

2023-08-24 14:54 UTC, cicalese commented on _sources/configs/composer.canasta.json
>  			"include": [
DataTransfer requires [phpoffice/phpspreadsheet](https://packagist.org/packages/phpoffice/phpspreadsheet), which requires [psr/http-client](https://packagist.org/packages/psr/http-client), which requires [psr/http-message](https://packagist.org/packages/psr/http-message) version ^1.0 || ^2.0. The error I was getting indicated that by the time DataTransfer was being resolved, http-message version 2.0 had already been selected. It indicated that there http-message 2.0 requires PHP 8, which could not be satisfied, although the spec for http-message says it accepts php: ^7.2 || ^8.0. Basically, it seems that composer got confused, but pegging the version to 1.1 for now fixes the issue.
I got this error when I was running composer update from the command line inside the container after the initial container creation. I had downloaded a patched version of Semantic MediaWiki (to test [this patch](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5451)). This required me to remove the vendor directory (because otherwise I was getting the SemanticBreadcrumbs not an entrypoint error) and run composer update. With the require statement above, all worked perfectly (including running Semantic MediaWiki with the ElasticStore backend).

2023-08-24 15:04 UTC, yaronkoren commented on _sources/configs/composer.canasta.json
>  			"include": [
Thanks for that detailed explanation - that's very helpful. Now I'm curious about that "vendor" problem - is that something that can be fixed in Canasta? By patching the SemanticBreadcrumbLinks code, possibly?

Also, does this change need to go into this patch, or can it be done separately, i.e. in an earlier patch?

2023-08-24 15:22 UTC, yaronkoren commented on _sources/configs/composer.canasta.json
>  			"include": [
Man. Another option is to just get rid of SemanticBreadcrumbLinks - it seems like a pretty useless extension, and I don't know why we ever agreed to include it in the first place. (We clearly didn't think it would cause problems!)

I'll create a separate patch, then.

2023-08-24 15:26 UTC, yaronkoren commented on _sources/configs/composer.canasta.json
>  			"include": [
Okay, done at #282.

2023-08-24 16:09 UTC, vedmaka commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties $MW_HOME/extensions/SemanticExtraSpecialProperties \
Same thing as with the above, there is an `autoload` section present https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/composer.json#L55

2023-08-24 16:14 UTC, vedmaka commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
Please note that the `require` is not the only reason we load extension via Composer, there is also an `autoload` section which is necessary for PSR autoloading https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/composer.json#L20 https://getcomposer.org/doc/04-schema.md#autoload

2023-08-24 16:17 UTC, vedmaka commented on _sources/configs/composer.canasta.json
>  			"include": [
Noting that this was fixed on recent MW versions https://github.com/wikimedia/mediawiki/commit/35cdb41d83c17d56e200824ce56b9d14723586ec

2023-08-24 16:22 UTC, cicalese commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticScribunto $MW_HOME/extensions/SemanticScribunto \
I suggest patching the extension.json file to add an autoload section (and submitting a patch upstream) rather then using composer autoloading for SemanticScribunto.

2023-08-24 16:22 UTC, cicalese commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticCompoundQueries $MW_HOME/extensions/SemanticCompoundQueries \
I suggest patching the extension.json file to add an autoload section (and submitting a patch upstream) rather then using composer autoloading for SemanticCompoundQueries.

2023-08-24 16:29 UTC, cicalese commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
But, that autoload section is not necessary for some of the extensions, which also specify autoloading in their extension.json files. See https://github.com/CanastaWiki/Canasta/pull/274#issuecomment-1681466506.

2023-08-24 16:53 UTC, cicalese commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
@vedmaka Do you agree that if autoloading is done in extension.json rather than composer.json, it is no longer necessary to include the composer.json files for those extensions in composer.canasta.json? Is there any other reason that those composer.json files must be included?

2023-08-24 16:59 UTC, yaronkoren commented
The conversation in the code has become chaotic (five separate discussions), so let me try to bring it all inline.

As I understand it, there are five extensions that are being discussed here, because they all include an "autoload" call in their composer.json file, which means that they need to be called with "composer update": Semantic Compound Queries (SCQ), Semantic Extra Special Properties (SESP), Semantic Scribunto (SS), Semantic Tasks (ST) and Semantic Forms Select (SFS). (There are other SMW-based extensions that also include the Composer "autoload", like SRF, SBL and SMW itself, but these need to get a "composer update" regardless because of their dependencies, so it doesn't matter.)

I think the whole "Composer autoload" thing is dumb, but it's not my decision. At this point, from what I understand, we have to deal with it in one of two ways: add all five of these extensions to composer.local.json or composer.canasta.json (ST and SFS are already there), or patch all five extensions to add an "autoload" to their extension.json.

@cicalese and @vedmaka - is that description correct? And if so, any preferences on what to do? My own inclination is to go with Cindy's recommendation to patch all five extensions - the less we have to deal with Composer, the better, I think.

2023-08-24 17:14 UTC, cicalese commented
> @cicalese and @vedmaka - is that description correct? And if so, any preferences on what to do? My own inclination is to go with Cindy's recommendation to patch all five extensions - the less we have to deal with Composer, the better, I think.

One correction. Of the five extensions in question, three of them already specify autoloading in their extension.json files, so we can safely remove them from composer.canasta.json and remove any patches created in this PR. Those extensions are 
Semantic Extra Special Properties (SESP), Semantic Tasks (ST) and Semantic Forms Select (SFS).

The other two extensions are missing autoload sections in their extension.json files: Semantic Compound Queries (SCQ) and Semantic Scribunto (SS). Those are the only two that I suggest we patch their extension.json files.

2023-08-24 18:41 UTC, vedmaka commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties $MW_HOME/extensions/SemanticExtraSpecialProperties \
Good point, that's right! If there is an autoload in the `extension.json`, then the one in the `composer.json` can be ignored

2023-08-24 18:43 UTC, vedmaka commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticCompoundQueries $MW_HOME/extensions/SemanticCompoundQueries \
that's good idea, especially considering there is a `file` autoload which is not cool https://github.com/SemanticMediaWiki/SemanticCompoundQueries/blob/master/composer.json#L44

2023-08-24 18:45 UTC, vedmaka commented on _sources/patches/semantic-tasks-composer-reqs.patch
> +-	},
Yes, if there is an autoload NS/Classes on the extension scheme (and there are no meaningful `requires` ), it's okay to ignore this section on the composer file

2023-08-24 18:47 UTC, vedmaka commented on _sources/patches/semantic-forms-select-composer-reqs.patch
> + 	},
That's right, I did miss the autoload on the extension.json

2023-08-24 18:55 UTC, cicalese commented on Dockerfile
>  	&& git checkout 4b56baa752401b4ff9fe555fd57fc5c3309601d4 \
add -q flag

2023-08-24 19:01 UTC, yaronkoren commented on Dockerfile
>  	&& git checkout 4b56baa752401b4ff9fe555fd57fc5c3309601d4 \
Right, I noticed that before. I think the "-q" is not strictly necessary, although it's good at least for consistency. This fix probably belongs in a separate patch, though.

2023-08-24 19:09 UTC, cicalese commented on Dockerfile
>  	&& git checkout 4b56baa752401b4ff9fe555fd57fc5c3309601d4 \
True, this line was not introduced here.

2023-08-24 19:13 UTC, vedmaka commented
> @cicalese and @vedmaka - is that description correct? 

yep (+taking into account @cicalese comment)

> And if so, any preferences on what to do? My own inclination is to go with Cindy's recommendation to patch all five extensions

That's right, in this situation, we either patch the extensions `extension.json` or the `composer.json`

> the less we have to deal with Composer, the better, I think.

I am unsure if dealing less with Composer is the right thing to do in the long term. The discussion about using Composer as a main extensions management tool [[1]](https://www.mediawiki.org/wiki/Composer/For_extensions) is still in progress [here](https://phabricator.wikimedia.org/T250406). It could be that managing all the extensions via composer (even non-Composer ones) is a good idea, especially considering the `update` problem is somewhat solved here https://github.com/wikimedia/composer-merge-plugin/commit/1b1afcb69fe9fae36eec90d4f3c865e0e79dfff1 and here https://github.com/wikimedia/composer-merge-plugin/pull/257

In theory, this provides a good number of benefits, like having a parsable composer file on the image instead of tons of `git clone ..` commands and a free version and extensions dependencies checks on extensions being installed

2023-08-24 19:22 UTC, yaronkoren commented
Thanks to both of you for your comments. @vedmaka - you may be right that, in the future, a pure Composer-based approach will be the way to go. For now, though, this kind of hybrid approach seems to be causing unnecessary complexity and difficulty, both for admins and for us developers.

I have been making changes to the code and to this PR, based on the recommendations. I think the big thing left to do now is to create patches for SCQ and SS. I'm not sure what to do add to extension.json for either extension - can anyone offer a hint?

2023-08-24 19:27 UTC, cicalese commented
> I have been making changes to the code and to this PR, based on the recommendations. I think the big thing left to do now is to create patches for SCQ and SS. I'm not sure what to do add to extension.json for either extension - can anyone offer a hint?

I was going to work on patches for those two, but I'm currently having trouble running with this patch. I see that there is a merge conflict in the composer.canasta.json file that needs to be resolved. Could you please fix that? The error I'm getting is that it is missing Vector, though, so I'm not sure that's related. I'll let you know if I determine there's another issue.

2023-08-24 19:33 UTC, yaronkoren commented
Oh yeah, I should have noticed that merge conflict. I just fixed it, I think.

2023-08-24 20:24 UTC, cicalese commented
> I think the big thing left to do now is to create patches for SCQ and SS. I'm not sure what to do add to extension.json for either extension - can anyone offer a hint?

For SemanticCompoundQueries/extension.json:
- replace:
	"load_composer_autoloader":true,
- with:
	"AutoloadNamespaces": {
		"SCQ\\": "src/"
	},
	"AutoloadClasses": {
		"SemanticCompoundQueries": "SemanticCompoundQueries.php"
	},

For SemanticScribunto/extension.json:
- replace:
	"load_composer_autoloader":true,
- with:
	"AutoloadNamespaces": {
		"SMW\\Scribunto\\": "src/"
	},
	"AutoloadClasses": {
		"SemanticScribunto": "SemanticScribunto.php"
	},

I successfully tested these modifications on my local instance.

2023-08-24 21:28 UTC, yaronkoren commented
Okay, thanks, that's great! Are you sure that the "load_composer_autoloader" lines to be removed, though? They're there for some of the other extensions:

https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/extension.json#L35
https://github.com/SemanticMediaWiki/SemanticFormsSelect/blob/master/extension.json#L66

2023-08-24 21:32 UTC, cicalese commented
> Okay, thanks, that's great! Are you sure that the "load_composer_autoloader" lines to be removed, though? They're there for some of the other extensions:
> 
> https://github.com/SemanticMediaWiki/SemanticTasks/blob/master/extension.json#L35 https://github.com/SemanticMediaWiki/SemanticFormsSelect/blob/master/extension.json#L66

Yes. See https://www.mediawiki.org/wiki/Manual:Extension.json/Schema#load_composer_autoloader. Since those extensions do not have any dependencies on libraries that are specified in composer.json, that line can/should be removed. It should actually be removed from the other extensions you referenced as well, but that's a problem for another day.

2023-08-24 22:13 UTC, vedmaka commented
By the way, I believe the [load_composer_autoloader](https://www.mediawiki.org/wiki/Manual:Extension.json/Schema/en#load_composer_autoloader) documentation is not well worded. This flag forces local `./vendor/autoload.php` from the **extension directory** to be loaded. This has no use when the merge-plugin is in place because when the extension Composer file is loaded through the merge-plugin all the dependencies are added to the main autoload file and no `vendor` is present at the extension directory

2023-08-24 22:27 UTC, yaronkoren commented on Dockerfile
> +	&& git clone --single-branch -b master https://github.com/SemanticMediaWiki/SemanticCompoundQueries $MW_HOME/extensions/SemanticCompoundQueries \
I added a patch for SCQ.

2023-08-24 22:33 UTC, yaronkoren commented
I just added the autoload patches for SCQ and SS to this PR - including the "load_composer_autoloader" removal. If it turns out that this line is harmless, then it will be easy to, er, remove that removal. In any case, assuming this all works, it will be good to at least add those new autoload lines "upstream" to the SCQ and SS extensions.

2023-08-24 23:21 UTC, cicalese commented
Tested. LGTM.

2023-08-24 23:21 UTC, cicalese approved these changes

2023-08-25 17:03 UTC, vedmaka approved these changes

2023-08-25 18:24 UTC, merged