Rename run-apache.sh to setup-all.sh
WikiWorks/Canasta pull request #358
Opened 2024-02-16 13:26 UTC by yaronkoren

Fixes #217 .

2024-02-24 05:33 UTC, jeffw16 commented
This doesn't just set things up. It also runs everything over and over again; it's the "main thread" of the container after startup. I strongly prefer a different name.

2024-02-24 05:34 UTC, jeffw16 requested changes

2024-02-24 05:34 UTC, jeffw16 commented on Dockerfile
> +CMD ["/setup-all.sh"]
This is a misnomer too.

2024-02-26 03:59 UTC, yaronkoren commented
What name would you suggest?

2024-03-04 14:49 UTC, yaronkoren commented
@jeffw16 (or anyone else) - what about run-all.sh?

2024-03-04 17:51 UTC, jeffw16 commented
Honestly I think `run.sh` would be fine. `run-all.sh` is alright too.

2024-03-04 20:13 UTC, yaronkoren commented
Alright, it's now being renamed to run-all.sh. I like the new name - it reminds me of the renaming of the VEForPageForm extension to "VEForAll".

2024-03-08 19:33 UTC, jeffw16 approved these changes

2024-03-08 19:40 UTC, merged